apiVersion: v1
kind: Pod
metadata:
   name: nginx-multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: log-collector
      image: busybox
      command: ["sh", "-c", "tail -f /var/log/nginx/access.log"]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs
  volumes:
    - name: nginx-logs
      emptyDir: {}
